version: "3"
services:
  doccle-paperless-service:
    image: ghcr.io/zdaar/doccle-paperless:latest
    container_name: doccle-paperless-service
    environment:
      - DOCCLE_USERNAME=your_doccle_username
      - DOCCLE_PASSWORD=your_doccle_password
      - PAPERLESS_URL=http://your_paperless_url
      - PAPERLESS_TOKEN=your_paperless_token
    volumes:
      - ./downloaded_documents:/app/downloaded_documents
      - ./logs:/app/logs
    ports:
      - "5000:5000"
